name: test_build
on: [push , workflow_dispatch]
jobs: 
  clone_and_test_code:
     runs-on: ubuntu-latest 
     steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '11'
  build_the_code:
     runs-on: ubuntu-latest 
     steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name : create directory
        run: mkdir staging && cp target/*.war staging
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
           name: Package
           path: staging
        
