name: test_build
on: [push , workflow_dispatch]
jobs: 
  clone_and_test_code:
     
     runs-on: self-hosted
     steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name : create directory
        run: mkdir staging && cp target/*.war staging

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
           name: Package
           path: staging
    
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.9
        with:
           host: ${{ secrets.HOST}}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: ${{ secrets.PORT }}
           command_timeout: 30m
           script: | 
             echo "Nice Job!!!"    
